"""
can_reader/replay.py — Replay a CAN log file onto a virtual bus.

Allows full GUI development and testing without any hardware connected.
Reads logs in the format captured by tesla_bms_analyzer.py (ELM327 ATMA output)
or in standard python-can .log format.

Usage:
    python -m can_reader.replay --file fixtures/sample_6f2.log

On Linux you can also replay onto vcan0:
    python -m can_reader.replay --file sample.log --interface socketcan --channel vcan0
"""

from __future__ import annotations

import argparse
import re
import sys
import time
import threading
from pathlib import Path
from typing import Optional

import can

from config import CAN_BITRATE


# ── Log format parsers ────────────────────────────────────────────────────────

def parse_elm327_log(path: Path) -> list[tuple[float, int, bytes]]:
    """
    Parse raw ELM327 ATMA output (the format tesla_bms_analyzer.py reads).
    Returns list of (relative_timestamp, arbitration_id, data).
    Timestamps are synthesized at 1ms intervals since ELM327 doesn't provide them.
    """
    frames = []
    tight_re  = re.compile(r'^([0-9A-Fa-f]{3,8})([0-9A-Fa-f]+)$')
    spaced_re = re.compile(r'^([0-9A-Fa-f]{3,8})\s+([0-9A-Fa-f]{2}(?:\s+[0-9A-Fa-f]{2})+)$')

    ts = 0.0
    with open(path, "r", errors="replace") as f:
        for line in re.split(r'\r|\n|\^M', f.read()):
            line = line.strip()
            if not line:
                continue
            m = spaced_re.match(line) or tight_re.match(line)
            if m:
                try:
                    arb_id = int(m.group(1), 16)
                    data = bytes.fromhex(m.group(2).replace(" ", ""))
                    frames.append((ts, arb_id, data))
                    ts += 0.001   # synthesize 1ms gaps
                except (ValueError, Exception):
                    continue

    return frames


def parse_python_can_log(path: Path) -> list[tuple[float, int, bytes]]:
    """
    Parse a python-can .log file (generated by can.Logger).
    Format: "(timestamp) arbitration_id#data_hex"
    """
    frames = []
    re_line = re.compile(r'\(([0-9.]+)\)\s+\S+\s+([0-9A-Fa-f]+)#([0-9A-Fa-f]*)')
    with open(path, "r", errors="replace") as f:
        for line in f:
            m = re_line.match(line.strip())
            if m:
                try:
                    ts = float(m.group(1))
                    arb_id = int(m.group(2), 16)
                    data = bytes.fromhex(m.group(3)) if m.group(3) else b""
                    frames.append((ts, arb_id, data))
                except (ValueError, Exception):
                    continue
    return frames


def parse_log_file(path: Path) -> list[tuple[float, int, bytes]]:
    """Auto-detect log format and parse."""
    suffix = path.suffix.lower()
    if suffix == ".log":
        # Try python-can format first
        frames = parse_python_can_log(path)
        if frames:
            return frames
    # Fall back to ELM327 format
    return parse_elm327_log(path)


# ── Replay engine ─────────────────────────────────────────────────────────────

class BusReplayer:
    """
    Replays a parsed frame list onto a python-can bus.
    Maintains original timing ratios (can be sped up/slowed down).
    Loops continuously until stopped.
    """

    def __init__(
        self,
        frames: list[tuple[float, int, bytes]],
        bus: can.BusABC,
        speed: float = 1.0,   # 1.0 = real-time, 2.0 = double speed
        loop: bool = True,
    ):
        self._frames = frames
        self._bus = bus
        self._speed = speed
        self._loop = loop
        self._running = False
        self._thread: Optional[threading.Thread] = None

    def start(self) -> None:
        self._running = True
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self) -> None:
        self._running = False

    def _run(self) -> None:
        while self._running:
            if not self._frames:
                break

            # Normalize timestamps to start at 0
            t0 = self._frames[0][0]
            wall_start = time.monotonic()

            for ts, arb_id, data in self._frames:
                if not self._running:
                    return
                # Sleep to maintain timing
                target_wall = wall_start + (ts - t0) / self._speed
                sleep_s = target_wall - time.monotonic()
                if sleep_s > 0:
                    time.sleep(sleep_s)

                try:
                    msg = can.Message(
                        arbitration_id=arb_id,
                        data=data,
                        is_extended_id=arb_id > 0x7FF,
                        timestamp=time.time(),
                    )
                    self._bus.send(msg)
                except can.CanError:
                    pass

            if not self._loop:
                break
            # Small gap between loops
            time.sleep(0.1)


def create_replay_bus(
    log_path: Path,
    speed: float = 1.0,
    loop: bool = True,
) -> tuple[can.BusABC, BusReplayer]:
    """
    Create a virtual bus and start replaying a log file onto it.
    Returns (bus_to_read_from, replayer).
    The caller should call bus.recv() to receive the replayed frames.
    """
    frames = parse_log_file(log_path)
    if not frames:
        raise ValueError(f"No frames parsed from {log_path}")

    print(f"Loaded {len(frames)} frames from {log_path.name}")

    # Two virtual buses on the same channel — one to write, one to read
    write_bus = can.Bus(
        interface="virtual",
        channel="replay",
        receive_own_messages=False,
    )
    read_bus = can.Bus(
        interface="virtual",
        channel="replay",
        receive_own_messages=False,
    )

    replayer = BusReplayer(frames, write_bus, speed=speed, loop=loop)
    replayer.start()

    return read_bus, replayer


# ── CLI entry point ───────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description="Replay a CAN log file onto a virtual bus")
    ap.add_argument("--file", required=True, help="Log file path (.log or ELM327 .txt)")
    ap.add_argument("--speed", type=float, default=1.0,
                    help="Replay speed multiplier (default 1.0 = real-time)")
    ap.add_argument("--no-loop", action="store_true", help="Play once then exit")
    ap.add_argument("--interface", default="virtual",
                    choices=["virtual", "socketcan"],
                    help="Output bus interface (default: virtual)")
    ap.add_argument("--channel", default="replay",
                    help="Bus channel (default: replay for virtual, can0 for socketcan)")
    args = ap.parse_args()

    log_path = Path(args.file)
    if not log_path.exists():
        print(f"File not found: {log_path}", file=sys.stderr)
        return 1

    frames = parse_log_file(log_path)
    if not frames:
        print("No frames parsed from log file.", file=sys.stderr)
        return 1

    print(f"Loaded {len(frames)} frames. Replaying at {args.speed}x speed...")

    try:
        out_bus = can.Bus(
            interface=args.interface,
            channel=args.channel,
            bitrate=CAN_BITRATE,
            receive_own_messages=True,
        )
        replayer = BusReplayer(frames, out_bus, speed=args.speed, loop=not args.no_loop)
        replayer.start()

        print(f"Replaying on {args.interface}:{args.channel} — Ctrl+C to stop")
        while replayer._running:
            time.sleep(0.5)
    except KeyboardInterrupt:
        print("\nStopped.")
        replayer.stop()

    return 0


if __name__ == "__main__":
    sys.exit(main())
